from pypeg2 import attr, optional, maybe_some, List, attributes, parse

## how to do this with the HTML as well? The HTML gives a loose structure, but
## I really want to piece it back together.

grammar = [ optional(attr("General"))
          , optional(attr(""))
          , optional(attr("SIM"))
          , optional(attr(""))
          , optional(attr("Status"))
          , optional(attr(""))
          , optional(attr("Body\nDimensions"))
          , optional(attr(""))
          , optional(attr("Weight"))
          , optional(attr(""))
          , optional(attr("Display"))
          , optional(attr("Type"))
          , optional(attr(""))
          , optional(attr("Size"))
          , optional(attr(""))
          , optional(attr("Multitouch"))
          , optional(attr(""))
          , optional(attr("Protection"))
          , optional(attr(""))
          , optional(attr("Loudspeaker"))
          , optional(attr("Yes|no"))
          , optional(attr("3.5mm jack"))
          , optional(attr("Yes|No"))
          , optional(attr("Memory"))
          , optional(attr("Data"))
          , optional(attr(""))
          , optional(attr("Speed"))
          , optional(attr(""))
          , optional(attr("WLAN"))
          , optional(attr(""))
          , optional(attr("Bluetooth"))
          , optional(attr(""))
          , optional(attr("NFC"))
          , optional(attr("Yes|No"))
          , optional(attr("USB"))
          , optional(attr("Yes|No"))
          , optional(attr("Camera"))
          , optional(attr("Primary"))
          , optional(attr(""))
          , optional(attr("Secondary"))
          , optional(attr(""))
          , optional(attr("Features"))
          , optional(attr("OS"))
          , optional(attr(""))
          , optional(attr("Chipset"))
          , optional(attr(""))
          , optional(attr("CPU"))
          , optional(attr(""))
          , optional(attr("GPU"))
          , optional(attr(""))
          , optional(attr("Sensors"))
          , optional(attr(""))
          , optional(attr("Messaging"))
          , optional(attr(""))
          , optional(attr("Browser"))
          , optional(attr(""))
          , optional(attr("Radio"))
          , optional(attr(""))
          , optional(attr("GPS"))
          , optional(attr(""))
          , optional(attr("Colors"))
          , optional(attr("[,]")) # list, comma separated
          , optional(attr("Battery"))
          , optional(attr(""))
          , optional(attr("Misc"))
          , optional(attr("SAR US"))
          , optional(attr(""))
          , optional(attr("SAR EU"))
          , optional(attr(""))
          , optional(attr(""))
          ]
